export class Language {
  static factory = {
    main: ['Anyone', 'Anyone'],
    dashboard: ['仪表盘', 'Dashboard'],
    language: ['中文', 'English'],
    center: ['个人中心', 'Center'],
    profile: ['信息修改', 'Profile'],
    exit: ['退出系统', 'Exit'],
    add: ['新增', 'Add'],
    success: ['执行成功', 'Success'],
    failed: ['执行失败', 'Failed'],
    back: ['返回', 'Back'],
    submit: ['提交', 'Submit'],
    reset: ['重置', 'Reset'],
    cancel: ['取消', 'Cancel'],
    status: ['状态', 'Status'],
    action: ['操作', 'Action'],
    edit: ['编辑', 'Edit'],
    delete: ['删除', 'Delete'],
    checks_delete: ['删除选中', 'Delete Selected'],
    on: ['开启', 'On'],
    off: ['冻结', 'Off'],
    yes: ['是', 'Yes'],
    no: ['否', 'No'],
  };
}
